name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Generate project
      run: |
        mvn archetype:generate -DgroupId=org.eguys.hashing -DartifactId=java-project -DarchetypeArtifactId=maven-archetype-quickstart -DinteractiveMode=false
        git config user.name "Github Actions user"
        git config user.email "kr@eguys.org"
        git add .
        git commit -am "Maven project template"
        git push push origin master
    - name: Build with Maven
      run: mvn package --file pom.xml
