name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: |
        cd java-project
        mvn package --file pom.xml
        java -jar target/java-project-1.0-SNAPSHOT.jar 123456
        mvn deploy -Dregistry=https://maven.pkg.github.com/KondaReddyR -Dtoken=${{ github.token }}
        
